### ISSUE TITLE
Please add some tests

### ISSUE THREAD

**Issue by vladkampov** [rovchynnyk/crew#1]
Thanks for the summiting your test project.
Could I ask you add write some tests?
I see you've added jest config alredy,

**Comment by rovchynnyk** [comment]
@vladkampov I added some test. Let me know if I should add more

**Comment by vladkampov** [comment]
@rovchynnyk Test fails with `ReferenceError: moveUser is not defined`

**Comment by rovchynnyk** [comment]
@vladkampov 
Sorry, my bad
It was some debugging stuff. I have already fixed it.
Thanks for pointing

**Comment by vladkampov** [comment]
Thanks :)
