### ISSUE TITLE
Sources structure

### ISSUE THREAD

**Issue by vladkampov** [rovchynnyk/crew#3]
In your current solution I see all the components laying in the `components` folder. Sounds logic :)
From my point of view it will cause a structural mess if amount of components will be more than 10.
 
How would you structure your components in a big project?

**Comment by rovchynnyk** [comment]
In a case, we have a big project I would structure it using directories. Ex., we have lots of components that describe a stage functionality, so they probably should belong to /stages or so. Do I need to restructure my code or my explanation would be enough? :)

**Comment by vladkampov** [comment]
This "issue" doesn't required any coding but glad you're ready for it. What do you think about Atomic components pattern for example? (https://medium.com/@yejodido/atomic-components-managing-dynamic-react-components-using-atomic-design-part-1-5f07451f261f)

**Comment by rovchynnyk** [comment]
@vladkampov looks good. Thanks :)

**Comment by vladkampov** [comment]
Thanks.
